# -*- mode: ruby -*-

# vi: set ft=ruby :

boxes = [
    {
        :name => "controller",
        :eth1 => "192.168.10.5",
        :mem => "512",
        :cpu => "1",
		    :box => "rockylinux8.4controller/ansible1",
		    :sshport => "2222"
    },
    {
        :name => "server1",
        :eth1 => "192.168.10.20",
        :mem => "512",
        :cpu => "1",
		    :box => "ubuntu20.04node/ansible1",
		    :sshport => "2223"
    },
    {
        :name => "server2",
        :eth1 => "192.168.10.21",
        :mem => "512",
        :cpu => "1",
		    :box => "ubuntu20.04node/ansible1",
		    :sshport => "2224"
    }
]

Vagrant.configure(2) do |config|

	# Desactivar sincronización de la carpeta raiz.
	#config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
	
	boxes.each do |opts|
		config.vm.define opts[:name] do |subconfig|
			subconfig.vm.box = opts[:box]
			subconfig.vm.hostname = opts[:name]
			subconfig.vm.network "private_network", ip: opts[:eth1]
			subconfig.vm.network "forwarded_port", guest: 22, host: opts[:sshport], id: "ssh"
			subconfig.vm.provider "virtualbox" do |vb|
				vb.customize ["modifyvm", :id, "--name", opts[:name]]
				vb.customize ["modifyvm", :id, "--memory", opts[:mem]]
				vb.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
			end
		end
	end
	
	config.vm.provision "shell", inline: <<-SHELL
		echo 'export http_proxy="http://10.40.56.3:8080"' >> /etc/environment
		echo 'export https_proxy="http://10.40.56.3:8080"' >> /etc/environment
	SHELL
end
