# -*- mode: ruby -*-
# vi: set ft=ruby :


CONTROLLER_BOX_IMAGE = "centos7controller"
NODES_BOX_IMAGE = "ubuntu2004node"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "controller" do |subconfig|
    subconfig.vm.box = CONTROLLER_BOX_IMAGE
    subconfig.vm.hostname = "centos7controller"
    subconfig.vm.network "private_network", ip: "10.0.0.10"
    subconfig.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
    subconfig.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", 512]
	    vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--name", "controller"]
	  end
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "ubuntu2004node#{i}" do |subconfig|
      subconfig.vm.box = NODES_BOX_IMAGE
      subconfig.vm.hostname = "ubuntu2004node#{i}"
      subconfig.vm.network "private_network", ip: "10.0.0.#{i + 20}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "222#{i + 2}", id: "ssh"
      ### Configuracion de la "MV" para el proveedor "virtualbox"
      ### http://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
      subconfig.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 512]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--name", "ubuntu2004node#{i}"]
      end
    end
  end

  # Configurar proxy del sistema  
  config.vm.provision "shell", inline: <<-SHELL
    echo 'export http_proxy="http://10.40.56.3:8080"' >> /etc/environment
    echo 'export https_proxy="http://10.40.56.3:8080"' >> /etc/environment
  SHELL
end
